### ISSUE TITLE
A testing device ID required

### ISSUE THREAD

**Issue by akm15machine** [DSCKGEC/cleanurge-backend#11]
Please create and hand me a device ID to test the routes with the MCU.

-to the Database Administrator

**Comment by singhayushh** [comment]
I've created 4 devices with the following config:

1. 
```
code: "#9BR37E"
geo.coordinates: [-11.802893, 14.456887]
```
2. 
```
code: "#9BR37E"
geo.coordinates: [-11.802893, 14.456887]
```
3. 
```
code: "#9BR37E"
geo.coordinates: [-11.802893, 14.456887]
```
4. 
```
code: "#9BR37E"
geo.coordinates: [-11.802893, 14.456887]
```

Default value of level is null. You can check the other parameters available for any device [here](https://cleanurge.herokuapp.com/docs) [At the bottom of the page]

**Comment by anindyamitra15** [comment]
![image](https://user-images.githubusercontent.com/55695557/124443186-1829e400-dd9b-11eb-94ae-86ae41f74821.png)
Hewp!
