### ISSUE TITLE
Needed: Email UI built using HTML and CSS

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/cleanurge-backend#2]
#### Preface
You must have received emails asking you to verify your account after creating a new account over some platform. These emails are generally not just textual emails but have their own UI, which is actually coded using simple HTML and CSS. Example:

<img src="https://user-images.githubusercontent.com/52620158/115107748-73adb800-9f8a-11eb-8526-77020e6a0a6f.png" height=200 />

This is what this issue is about.

#### Changes needed
- In the `utils` directory, create a new file named `email.js`. The contents of the file are given below:
    ```js
    const email_ui = (email, name, link) => {
        const ui = `<HTML CODE GOES HERE>`
        return ui;
    }

    module.exports = email_ui;
    ```
- A UI for the email is to be designed using HTML, CSS and placed inside the email_ui variable. The email will thank the user for creating an account and provide him/her with a link to verify the account. The user's email, name and the link to verify the account are passed in the above function as `email`, `name` and `link` respectively. Do not forget to use these variables in the email's content. How the email should look is totally upto you!

**Comment by dp46504** [comment]
I can get it

**Comment by singhayushh** [comment]
Hey @dp46504 👋🏻 
Hope you're doing well!
Thank you for showing your interest in this issue

Here's some content below, feel free to modify it as you like, if you may
```
Dear <name>,
Welcome to Cleanurge.

Thanks for signing up! We made Cleanurge to solve the challenges of waste management by bridging the gap between residents and municipalities.

Now, you're one step closer to help solve the challenges of waste management. Verify your email by clicking on the email below to start using the Cleanurge platform.
<link>

We're here every step of the way. If you have any questions, just reply to this email and it would be our pleasure to help.
Student Developer Team,
DSC KGEC.
```

**Comment by dp46504** [comment]
Ok i will start working on this ;)

**Comment by singhayushh** [comment]
There is no hurry, you may take your time
Thanks again!
